SELECT 
SYSDATE AS DATA_ATUAL,
FUNCIONARIOS.CODINTFUNC,
FUNCIONARIOS.CHAPAFUNC AS MATRICULA,
FUNCIONARIOS.SALBASE,
FUNCIONARIOS.NOMECOMPLETOFUNC AS NOME,
FUNCIONARIOS.DESCFUNCAOCOMPLETA,
FUNCIONARIOS.DESCAREA,
FUNCIONARIOS.DESCSECAO AS FILIAL,
CASE WHEN TO_CHAR(BANCOHORAS.COMPETENCIA, 'MM') = 1 THEN 'PGTO FEV'
     WHEN TO_CHAR(BANCOHORAS.COMPETENCIA, 'MM') = 2 THEN 'PGTO AGO'
     WHEN TO_CHAR(BANCOHORAS.COMPETENCIA, 'MM') = 3 THEN 'PGTO AGO'
     WHEN TO_CHAR(BANCOHORAS.COMPETENCIA, 'MM') = 4 THEN 'PGTO AGO'
     WHEN TO_CHAR(BANCOHORAS.COMPETENCIA, 'MM') = 5 THEN 'PGTO AGO'
     WHEN TO_CHAR(BANCOHORAS.COMPETENCIA, 'MM') = 6 THEN 'PGTO AGO'
     WHEN TO_CHAR(BANCOHORAS.COMPETENCIA, 'MM') = 7 THEN 'PGTO AGO'
     WHEN TO_CHAR(BANCOHORAS.COMPETENCIA, 'MM') = 8 THEN 'PGTO FEV'
     WHEN TO_CHAR(BANCOHORAS.COMPETENCIA, 'MM') = 9 THEN 'PGTO FEV'
     WHEN TO_CHAR(BANCOHORAS.COMPETENCIA, 'MM') = 10 THEN 'PGTO FEV'
     WHEN TO_CHAR(BANCOHORAS.COMPETENCIA, 'MM') = 11 THEN 'PGTO FEV'
     WHEN TO_CHAR(BANCOHORAS.COMPETENCIA, 'MM') = 12 THEN 'PGTO FEV'
     ELSE '' END AS COMP_PGTO,
BANCOHORAS.COMPETENCIA,
BANCOHORAS.MESANTERIOR,
BANCOHORAS.CREDITO,
BANCOHORAS.DEBITO,
BANCOHORAS.SALDONACOMPET,
BANCOHORAS.SALDOANTERIOR,
CASE WHEN BANCOHORAS.VALORPAGO IS NULL THEN 0 ELSE BANCOHORAS.VALORPAGO END AS VALORPAGO
FROM FRQ_BANCOHORAS BANCOHORAS
LEFT JOIN VW_FUNCIONARIOS FUNCIONARIOS ON BANCOHORAS.CODINTFUNC = FUNCIONARIOS.CODINTFUNC
WHERE FUNCIONARIOS.SITUACAOFUNC = 'A' AND FUNCIONARIOS.CODIGOEMPRESA = 1 --AND BANCOHORAS.DTPAGAMENTO IS NULL
ORDER BY FUNCIONARIOS.NOMECOMPLETOFUNC, BANCOHORAS.COMPETENCIA