SELECT 
SYSDATE AS DATA_ATUAL,
FF.CODFUNC,
FF.NOMECOMPLETOFUNC,
CPF.NRDOCTO AS CPF,
FD.NRDOCTO,
FD.CNHCATDOCTO,
FD.DTDOCTO AS VALIDADE,
FD.CNHCODIGOUF,
CASE WHEN FD.DTDOCTO - SYSDATE < 0 THEN 'VENCIDA' 
  WHEN FD.DTDOCTO - SYSDATE < 10 THEN 'ATÉ 10 DIAS' 
  WHEN FD.DTDOCTO - SYSDATE < 30 THEN 'ATÉ 30 DIAS' 
  WHEN FD.DTDOCTO - SYSDATE < 60 THEN 'ATÉ 60 DIAS' 
  ELSE 'ACIMA DE 60 DIAS' END AS faixas_tempo,
vf.DESCFUNCAOCOMPLETA,
vf.DESCAREA
FROM FLP_DOCUMENTOS fd
LEFT JOIN FLP_DOCUMENTOS CPF ON FD.CODINTFUNC = CPF.CODINTFUNC AND CPF.TIPODOCTO = 'CPF'
LEFT JOIN FLP_FUNCIONARIOS ff ON FD.CODINTFUNC = FF.CODINTFUNC
LEFT JOIN VW_FUNCIONARIOS vf ON FD.CODINTFUNC = VF.CODINTFUNC
WHERE FD.TIPODOCTO = 'CNH' AND ff.SITUACAOFUNC = 'A' AND FF.CODIGOEMPRESA = 1 AND vf.DESCFUNCAOCOMPLETA LIKE 'MOTO%'
ORDER BY ff.CODFUNC DESC