SELECT 
VW_FUNCIONARIOS.NOMECOMPLETOFUNC,
VW_FUNCIONARIOS.DESCAREA,
FLP_DEPENDENTES.NOMECOMPLETODEPEN,
FLP_PARENTESCO.DESCPAREN

FROM FLP_DEPENDENTES
LEFT JOIN FLP_PARENTESCO ON FLP_DEPENDENTES.CODPAREN = FLP_PARENTESCO.CODPAREN
LEFT JOIN VW_FUNCIONARIOS ON FLP_DEPENDENTES.CODINTFUNC = VW_FUNCIONARIOS.CODINTFUNC
WHERE FLP_DEPENDENTES.CODPAREN = 3 AND VW_FUNCIONARIOS.CODIGOEMPRESA = 1 AND VW_FUNCIONARIOS.SITUACAOFUNC IN ('A') AND VW_FUNCIONARIOS.SEXOFUNC = 'M'