SELECT 
VF.CODFUNC,
VF.NOMEFUNC,
VF.DESCFUNCAOCOMPLETA,
VF.DESCAREA,
VF.SEXOFUNC,
VFF.COMPETFICHA,
TO_CHAR(VFF.COMPETFICHA, 'MM/YYYY') AS COMPET,
VFF.TIPOFOLHA,
VFF.TIPOEVEN,
VFF.CODEVENTO,
VFF.DESCEVEN,
VFF.REFERENCIA,
VFF.VALORFICHA
FROM VW_FLP_FICHAEVENTOSRECIBO vff
LEFT JOIN VW_FUNCIONARIOS vf ON VFF.CODFUNC = VF.CODFUNC
WHERE TO_CHAR(VFF.COMPETFICHA, 'MM/YYYY') = '06/2023' AND VF.DESCFUNCAOCOMPLETA LIKE '%MOTO%' --VF.CODFUNC = 3416 AND 

/*
CODFUNCIONARIO
NOME FUNCIONARIO
CENTRO DE CUSTO / AREA
COMPETENCIA
TIPO FOLHA
CODEVENTO
NOME DO EVENTO
VALOR EVENTO
*/