SELECT FUNCIONARIOS.NOMECOMPLETOFUNC,
FUNCIONARIOS.DESCAREA,
FUNCIONARIOS.DESCFUNCAOCOMPLETA,
FERIAS.*,
ADD_MONTHS(FERIAS.PROXAQUIFINFER, 11) AS LIMITE_FERIAS,
ROUND(ADD_MONTHS(FERIAS.PROXAQUIFINFER, 11) - SYSDATE,2) AS TEMPO_LIMITE_DIAS,
CASE WHEN ROUND(ADD_MONTHS(FERIAS.PROXAQUIFINFER, 11) - SYSDATE,2) < 0 THEN 'VENCIDA'
     WHEN ROUND(ADD_MONTHS(FERIAS.PROXAQUIFINFER, 11) - SYSDATE,2) < 30 THEN 'ATÉ 30 DIAS'
     WHEN ROUND(ADD_MONTHS(FERIAS.PROXAQUIFINFER, 11) - SYSDATE,2) < 90 THEN 'ATÉ 90 DIAS'
     WHEN ROUND(ADD_MONTHS(FERIAS.PROXAQUIFINFER, 11) - SYSDATE,2) < 120 THEN 'ATÉ 120 DIAS'
     ELSE 'ACIMA DE 120 DIAS' END AS FAIXAS
FROM VW_FERIAS FERIAS
LEFT JOIN VW_FUNCIONARIOS FUNCIONARIOS ON FERIAS.CODINTFUNC = FUNCIONARIOS.CODINTFUNC
WHERE FUNCIONARIOS.SITUACAOFUNC = 'A' --AND FUNCIONARIOS.NOMECOMPLETOFUNC LIKE 'LEANDRO%'--AND FERIAS.AQUIINIFER IS NOT NULL 
ORDER BY FERIAS.AQUIINIFER DESC
