SELECT 
SYSDATE AS DATA_ATUAL,
VF.CODIGOEMPRESA,
VF.CHAPAFUNC AS MATRICULA,
VF.DTADMFUNC AS DT_ADM,
VF2.SITUACAOREAL,
ROUND((SYSDATE - VF.DTADMFUNC) / 30,2)  AS TEMPO_CASA,
ROUND(((SYSDATE - VF.DTADMFUNC) / 30)/12,2)  AS TEMPO_CASA_ANOS,
CASE WHEN ROUND(SYSDATE - VF.DTADMFUNC,2) / 30 <= 3 THEN '01 - ATÉ 3 MESES'
     WHEN ROUND(SYSDATE - VF.DTADMFUNC,2) / 30 <= 6 THEN '02 - ATÉ 6 MESES'
     WHEN ROUND(SYSDATE - VF.DTADMFUNC,2) / 30 <= 12 THEN '03 - ATÉ 1 ANO'
     WHEN ROUND(SYSDATE - VF.DTADMFUNC,2) / 30 <= 24 THEN '04 - ATÉ 2 ANOS'
     WHEN ROUND(SYSDATE - VF.DTADMFUNC,2) / 30 <= 36 THEN '05 - ATÉ 3 ANOS'
     WHEN ROUND(SYSDATE - VF.DTADMFUNC,2) / 30 <= 48 THEN '06 - ATÉ 4 ANOS'
ELSE '07 - ACIMA DE 4 ANOS' END AS FAIXA_TEMPO_CASA,
VF.DTNASCTOFUNC AS DT_NASC,
VF.NOMECOMPLETOFUNC AS NOME,
VF.DESCFUNCAOCOMPLETA AS FUNCAO,
CASE WHEN VF.DESCFUNCAOCOMPLETA LIKE 'COORD%' OR VF.DESCFUNCAOCOMPLETA LIKE 'SUPERV%' OR VF.DESCFUNCAOCOMPLETA LIKE 'GERENTE%' OR VF.DESCFUNCAOCOMPLETA LIKE 'DIRETOR%' OR VF.DESCFUNCAOCOMPLETA LIKE 'CONTADO%' OR VF.DESCFUNCAOCOMPLETA LIKE 'VICE%' OR VF.DESCFUNCAOCOMPLETA LIKE 'BUSINESS%' THEN 'LIDERANÇA'
ELSE 'COLABORADOR' END AS LIDER,
VF.CODFUNCAO,
VF.DESCFUNCAO,
VF.CODSINDI,
VF.SEXOFUNC AS SEXO,
FR.DESCRACA AS RACA,
FD.DESCDEF AS DEFICIENCIA,
VF.DESCESTCIV AS ESTADO_CIVIL,
VF.DESCAREA AS AREA,
VF.CODAREA AS COD_AREA,
VF.DESCDEPTO AS DEPTO,
VF.CODSECAO AS COD_FILIAL,
VF.DESCSECAO AS FILIAL,
VF.SALBASE,
FA.DTAFAST,
ROUND(SYSDATE - FA.DTAFAST,0) AS TEMPO_AFASTADO,
FA.DTRETAFAST,
VF.SITUACAOFUNC
FROM VW_FUNCIONARIOS vf
LEFT JOIN FLP_RACACOR fr ON VF.CODRACA = FR.CODRACA
LEFT JOIN FLP_AFASTADOS fa ON VF.CODINTFUNC = FA.CODINTFUNC AND FA.DTRETAFAST IS NULL
LEFT JOIN FLP_DEFICIENTEFISICO_FUNC fdf ON VF.CODINTFUNC = FDF.CODINTFUNC
LEFT JOIN FLP_DEFICIENTEFISICO fd ON FDF.CODDEF = FD.CODDEF
LEFT JOIN VW_FUNCIONARIOSSIT vf2 ON VF.CODINTFUNC = VF2.CODINTFUNC
WHERE VF.CODIGOEMPRESA = 1 AND VF.SITUACAOFUNC IN ('A') AND VF.DESCDEPTO LIKE '%MOT%'  AND VF.NOMECOMPLETOFUNC LIKE '%LARIS%' --AND ROUND(SYSDATE - FA.DTAFAST,0) > 0-- 

--ORDER BY VF.SALBASE DESC
ORDER BY ROUND((SYSDATE - VF.DTADMFUNC) / 30,2) DESC