SELECT
SYSDATE AS DATA_ATUAL, 
FF.COMPETFICHA,
TO_CHAR(FF.COMPETFICHA, 'YYYY') AS ANO,
VF.NOMEFUNC,
VF.DESCFUNCAO,
VF.DESCAREA,
VF.DESCSECAO,
VF.DESCDEPTO,
FE.DESCEVEN,
CASE WHEN FE.DESCEVEN LIKE '%50%%' THEN 'HE 50%'
ELSE 'HE 100%' END AS DESCEVEN_RESUMIDO,
FF.REFERENCIA,
FF.VALORFICHA,
FF.TIPOFOLHA
FROM FLP_FICHAEVENTOS FF
LEFT JOIN FLP_EVENTOS FE ON FF.CODEVENTO = FE.CODEVENTO
LEFT JOIN VW_FUNCIONARIOS VF ON ff.CODINTFUNC = VF.CODINTFUNC
WHERE FF.TIPOFOLHA = '1' AND FE.DESCEVEN LIKE '%50%%' OR FE.DESCEVEN LIKE '%100%%' AND TO_CHAR(FF.COMPETFICHA, 'YYYY') = 2023
ORDER BY FF.COMPETFICHA DESC, VF.NOMEFUNC