SELECT
CTBCONTA.CODCONTACTB,
CTBCONTA.CLASSIFICADOR,
UPPER(CTBCONTA.NOMECONTA) NOMECONTA,
FLP_INTEGRACAOCONTABIL.CODIGOFL,
FLP_INTEGRACAOCONTABIL.CODAGREVEN,
FLP_AGRUPAEVENTOS.DESCAGREVEN,
FLP_AGRUPACTB.DESCAGRCTB


FROM CTBCONTA, FLP_INTEGRACAOCONTABIL, FLP_AGRUPAEVENTOS, FLP_AGRUPACTB

WHERE CTBCONTA.CODCONTACTB = FLP_INTEGRACAOCONTABIL.CODCONTA

AND FLP_INTEGRACAOCONTABIL.CODAGRCTB = FLP_AGRUPACTB.CODAGRCTB

AND FLP_AGRUPAEVENTOS.CODAGREVEN = FLP_INTEGRACAOCONTABIL.CODAGREVEN AND FLP_AGRUPAEVENTOS.TIPOAGREVEN = 100

AND CTBCONTA.APURACAO = 'S'