SELECT 
EVENTOS.CODEVENTO,
EVENTOS.DESCEVEN,
FUNCIONARIOS.DESCAREA AS CC,
EVENTOS.TIPOFOLHA,
EVENTOS.TIPOEVEN,
EVENTOS.VALORFICHA
FROM VW_FICHAFINANEVENTOS EVENTOS
LEFT JOIN VW_FUNCIONARIOS FUNCIONARIOS ON EVENTOS.CODFUNC = FUNCIONARIOS.CODFUNC
WHERE TO_CHAR(EVENTOS.COMPETFICHA, 'DD/MM/YYYY') = '30/04/2024'